### ISSUE TITLE
octomap.lunch報錯

### ISSUE THREAD

**Issue by weizhi0304** [Zhu-Liyuan/ORB-SLAM2_RGBD_DENSE_MAP#1]
我運行octomap.lunch的時候，會持續發布以下錯誤
`Nothing to publish, octree is empty`
請問是哪邊沒有設定好

**Comment by peanut-nav** [comment]
我测试了一下，发现其实是因为octomap订阅的/point_cloud_dense中的数据为空，如果将octomap.launch文件中的point_cloud_dense换为point_cloud_ref的话可以避免这个问题，但是point_cloud_ref的点是稀疏的，因此建的八叉树地图并不理想。
以上是我在树莓派上运行时遇到的问题。
但我在电脑虚拟机上运行时就不会出现这样的问题，point_cloud_dense也是有数据的，效果也很理想。

随带一提，我的电脑虚拟机是ubuntu16.04，树莓派是ubuntu18.04，不确定是否有这个原因。

**Comment by sun1f** [comment]
我也是，point_cloud_dense里面没数据，咋解决啊。ubuntu20双系统
